Get http://localhost:3000/movies/
###
POST http://localhost:3000/movies/
Content-Type: application/json

{
  "directorId": 99,
  "movieName": "abc",
  "leadActor": "xyz"
}
###

GET http://localhost:3000/movies/2
###